# Generated by Django 4.1.13 on 2025-11-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_uploadeddocument_delete_chathistory_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
